import type { Metadata } from "next";
import "./globals.css";
import { getDb } from "@/db/drizzle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const db = getDb();

  return <html lang="en">{children}</html>;
}
