name: Deploy Development

on:
  push:
    branches: ["main"]

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ltelle-eatery:dev
          file: ./Dockerfile
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/ltelle-eatery:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/ltelle-eatery:buildcache,mode=max

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ../home/apps
            docker compose pull app_dev
            docker compose up app_dev -d --force-recreate
